"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { WorkspaceShell } from "@/components/workspace-shell";
import { Button } from "@/components/ui/button";
import { ApiError, downloadBlob } from "@/lib/api-client";
import type { ElectionResponse, SendVoterInvitationsResponse, VoterRollEntryResponse, VoterRollImportResponse } from "@/lib/types";
import { useRequireAuth } from "@/lib/use-require-auth";

export default function VoterRollPage() {
  const { electionId } = useParams<{ electionId: string }>(); const { user, loading, authGet, authPost, authDelete } = useRequireAuth();
  const [election, setElection] = useState<ElectionResponse | null>(null); const [entries, setEntries] = useState<VoterRollEntryResponse[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [reload, setReload] = useState(0); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (loading || !user) return; void Promise.all([authGet<ElectionResponse>(`/api/v1/elections/${electionId}`), authGet<VoterRollEntryResponse[]>(`/api/v1/elections/${electionId}/voter-roll`)]).then(([record, rows]) => { setElection(record); setEntries(rows); setBusy(false); }).catch((reason: unknown) => { setError(reason instanceof ApiError ? reason.message : "Unable to load voter roll."); setBusy(false); }); }, [loading, user, authGet, electionId, reload]);
  if (loading || !user || busy) return <main className="grid min-h-screen place-items-center">Loading voter roll…</main>;
  if (!election) return <main className="grid min-h-screen place-items-center text-destructive">{error}</main>;
  const canEdit = ["DRAFT", "SCHEDULED"].includes(election.status);
  const importCsv = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const file = fileRef.current?.files?.[0]; if (!file) return; const form = new FormData(); form.append("file", file); try { const result = await authPost<VoterRollImportResponse>(`/api/v1/elections/${electionId}/voter-roll/import`, form); setMessage(`Imported ${result.imported_count}; skipped ${result.duplicate_count} duplicate(s); ${result.error_count} error(s).`); setReload(value => value + 1); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Import failed."); } };
  const invite = async () => { try { const result = await authPost<SendVoterInvitationsResponse>(`/api/v1/elections/${electionId}/voter-invitations/send`, { channels: ["EMAIL", "SMS"] }); setMessage(`Issued ${result.invited_count} secure link(s): ${result.email_count} email and ${result.sms_count} SMS.`); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to send invitations."); } };
  return <WorkspaceShell admin={user.is_super_admin}><main className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6"><Link href={`/elections/${electionId}`} className="inline-flex min-h-11 items-center text-sm text-muted-foreground">← Election</Link><h1 className="font-heading text-3xl font-bold">Voter roll</h1><p className="mt-2 text-sm text-muted-foreground">{election.title} · {entries.length} eligible voter(s)</p>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}{message && <p role="status" className="mt-4 border bg-card p-4 text-sm">{message}</p>}
    {canEdit && <section className="mt-7 border bg-card p-5"><h2 className="font-heading text-xl font-semibold">Import CSV</h2><p className="mt-2 text-sm text-muted-foreground">Required column: external_voter_id. Optional delivery columns: email and phone.</p><form onSubmit={importCsv} className="mt-4 flex flex-wrap gap-3"><input ref={fileRef} type="file" accept=".csv" required className="min-h-11 flex-1 border bg-background p-2 text-sm" /><Button type="submit">Import</Button><Button type="button" variant="outline" onClick={() => downloadBlob(new Blob(["external_voter_id,email,phone\nEMP-1001,voter@example.com,+233241234567\n"], { type: "text/csv" }), "voter-roll-template.csv")}>Template</Button></form></section>}
    {entries.length > 0 && ["DRAFT", "SCHEDULED", "OPEN"].includes(election.status) && <Button type="button" className="mt-4" onClick={() => void invite()}>Send secure voting links</Button>}
    <section className="mt-8 divide-y border bg-card">{entries.length === 0 ? <p className="p-5 text-sm text-muted-foreground">No voters imported yet.</p> : entries.map(entry => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><span><strong>{entry.external_voter_id}</strong>{entry.email && <span className="ml-2 text-muted-foreground">{entry.email}</span>}{entry.phone && <span className="ml-2 text-muted-foreground">{entry.phone}</span>}</span>{canEdit && <button type="button" className="min-h-11 cursor-pointer px-2 text-xs font-semibold text-destructive" onClick={async () => { await authDelete(`/api/v1/elections/${electionId}/voter-roll/${entry.id}`); setReload(value => value + 1); }}>Remove</button>}</div>)}</section>
  </main></WorkspaceShell>;
}
