"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input";
import { ApiError } from "@/lib/api-client"; import type { BallotViewResponse, CastBallotResponse, PositionWithCandidatesResponse } from "@/lib/types"; import { useRequireAuth } from "@/lib/use-require-auth";
type State = { kind: "loading" | "verify" | "voted" | "done" | "error"; ballot?: BallotViewResponse; message?: string; receipts?: string[] };
export default function VotePage() {
  const { electionId } = useParams<{ electionId: string }>(); const { user, loading, authGet, authPost } = useRequireAuth(); const [state, setState] = useState<State>({ kind: "loading" }); const [voterId, setVoterId] = useState(""); const [selections, setSelections] = useState<Record<string, string[]>>({}); const [review, setReview] = useState(false); const [pending, setPending] = useState(false); const [key] = useState(() => crypto.randomUUID());
  const load = async () => { try { const ballot = await authGet<BallotViewResponse>(`/api/v1/elections/${electionId}/ballot`); setState(ballot.has_voted ? { kind: "voted" } : { kind: "loading", ballot }); } catch (reason) { if (reason instanceof ApiError && reason.code === "NOT_ELIGIBLE") setState({ kind: "verify" }); else setState({ kind: "error", message: reason instanceof ApiError ? reason.message : "Unable to load ballot." }); } };
  useEffect(() => { if (!loading && user) void load(); }, [loading, user]); // eslint-disable-line react-hooks/exhaustive-deps
  if (loading || !user) return <main className="grid min-h-screen place-items-center">Loading ballot…</main>;
  const toggle = (position: PositionWithCandidatesResponse, id: string) => setSelections(previous => { const selected = previous[position.id] ?? []; if (position.selection_max === 1) return { ...previous, [position.id]: [id] }; if (selected.includes(id)) return { ...previous, [position.id]: selected.filter(value => value !== id) }; return selected.length >= position.selection_max ? previous : { ...previous, [position.id]: [...selected, id] }; });
  const verify = async (event: FormEvent) => { event.preventDefault(); setPending(true); try { await authPost(`/api/v1/elections/${electionId}/eligibility/verify`, { external_voter_id: voterId || null }); await load(); } catch (reason) { if (reason instanceof ApiError && reason.code === "ALREADY_VERIFIED") await load(); else setState({ kind: "error", message: reason instanceof ApiError ? reason.message : "Verification failed." }); } finally { setPending(false); } };
  const cast = async () => { setPending(true); try { const result = await authPost<CastBallotResponse>(`/api/v1/elections/${electionId}/ballot/cast`, { selections: Object.entries(selections).flatMap(([position_id, ids]) => ids.map(candidate_id => ({ position_id, candidate_id }))) }, { "Idempotency-Key": key }); setState({ kind: "done", receipts: result.receipts }); } catch (reason) { setState(previous => ({ ...previous, kind: "error", message: reason instanceof ApiError ? reason.message : "Ballot submission failed." })); } finally { setPending(false); } };
  return <main className="mx-auto min-h-screen w-full max-w-2xl px-4 py-8 sm:px-6"><Link href={`/elections/${electionId}`} className="inline-flex min-h-11 items-center text-sm text-muted-foreground">← Election</Link>{state.kind === "verify" && <form onSubmit={verify} className="border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Verify eligibility</h1><p className="mt-2 text-sm text-muted-foreground">Your account email is checked first. Enter a voter ID only if your roll uses one.</p><Input value={voterId} onChange={e => setVoterId(e.target.value)} className="mt-5 h-11" placeholder="Voter ID (optional)" /><Button type="submit" disabled={pending} className="mt-3 h-11 w-full">Verify</Button></form>}{state.kind === "voted" && <p className="border bg-card p-6">You have already voted in this election.</p>}{state.kind === "done" && <section className="border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Vote recorded</h1><p className="mt-2 text-sm text-muted-foreground">Keep these anonymous verification receipts:</p><ul className="mt-4 space-y-2 font-mono text-xs">{state.receipts?.map(receipt => <li key={receipt} className="break-all border bg-secondary p-3">{receipt}</li>)}</ul></section>}{state.kind === "error" && <p role="alert" className="text-sm text-destructive">{state.message}</p>}{state.ballot && !review && <form onSubmit={event => { event.preventDefault(); setReview(true); }}><h1 className="font-heading text-3xl font-bold">Cast your vote</h1><p className="mt-2 text-sm text-muted-foreground">Ballot closes {new Date(state.ballot.end_at).toLocaleString()}.</p><div className="mt-6 space-y-5">{state.ballot.positions.map(position => <fieldset key={position.id} className="border bg-card p-5"><legend className="px-2 font-heading text-lg font-semibold">{position.title}</legend><div className="grid gap-3">{position.candidates.map(candidate => <label key={candidate.id} className="flex min-h-12 cursor-pointer items-center gap-3 border p-3"><input type={position.selection_max === 1 ? "radio" : "checkbox"} name={position.id} checked={(selections[position.id] ?? []).includes(candidate.id)} onChange={() => toggle(position, candidate.id)} /><span><strong className="block text-sm">{candidate.name}</strong>{candidate.bio && <span className="text-xs text-muted-foreground">{candidate.bio}</span>}</span></label>)}</div></fieldset>)}</div><Button type="submit" className="mt-5 h-11 w-full">Review ballot</Button></form>}{state.ballot && review && <section className="border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Review your ballot</h1><p className="mt-2 text-sm text-muted-foreground">Once submitted, your vote cannot be changed.</p><div className="mt-5 flex gap-3"><Button variant="outline" onClick={() => setReview(false)}>Go back</Button><Button disabled={pending} onClick={() => void cast()}>{pending ? "Submitting…" : "Submit ballot"}</Button></div></section>}</main>;
}
