"use client";
import Link from "next/link"; import { useParams } from "next/navigation"; import { useEffect, useState, type FormEvent } from "react"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { ApiError } from "@/lib/api-client"; import type { PositionWithCandidatesResponse } from "@/lib/types"; import { useRequireAuth } from "@/lib/use-require-auth";
export default function NominatePage() { const { electionId } = useParams<{ electionId: string }>(); const { user, loading, authGet, authPost } = useRequireAuth(); const [positions, setPositions] = useState<PositionWithCandidatesResponse[]>([]); const [position, setPosition] = useState(""); const [name, setName] = useState(""); const [statement, setStatement] = useState(""); const [voterId, setVoterId] = useState(""); const [verify, setVerify] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { if (!loading && user) void authGet<PositionWithCandidatesResponse[]>(`/api/v1/elections/${electionId}/nominations/positions`).then(setPositions).catch((reason: unknown) => setError(reason instanceof ApiError ? reason.message : "Unable to load positions.")); }, [loading, user, authGet, electionId]);
  if (loading || !user) return <main className="grid min-h-screen place-items-center">Loading…</main>;
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(""); try { await authPost(`/api/v1/elections/${electionId}/nominations`, { position_id: position, full_name: name, statement: statement || null }); setDone(true); } catch (reason) { if (reason instanceof ApiError && reason.code === "NOT_ELIGIBLE") setVerify(true); else setError(reason instanceof ApiError ? reason.message : "Nomination failed."); } finally { setPending(false); } };
  const verifyEligibility = async (event: FormEvent) => { event.preventDefault(); setPending(true); try { await authPost(`/api/v1/elections/${electionId}/eligibility/verify`, { external_voter_id: voterId || null }); setVerify(false); } catch (reason) { if (reason instanceof ApiError && reason.code === "ALREADY_VERIFIED") setVerify(false); else setError(reason instanceof ApiError ? reason.message : "Verification failed."); } finally { setPending(false); } };
  return <main className="mx-auto min-h-screen w-full max-w-xl px-4 py-8"><Link href={`/elections/${electionId}`} className="inline-flex min-h-11 items-center text-sm text-muted-foreground">← Election</Link>{error && <p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}{done ? <section className="border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Nomination submitted</h1><p className="mt-2 text-sm text-muted-foreground">The election organiser will review it before it appears on the ballot.</p></section> : verify ? <form onSubmit={verifyEligibility} className="border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Verify eligibility</h1><Input value={voterId} onChange={e => setVoterId(e.target.value)} className="mt-5 h-11" placeholder="Voter ID (optional)" /><Button type="submit" disabled={pending} className="mt-3 h-11 w-full">Verify</Button></form> : <form onSubmit={submit} className="space-y-4 border bg-card p-6"><h1 className="font-heading text-3xl font-bold">Nominate yourself</h1><div><label htmlFor="position" className="text-sm font-medium">Position</label><select id="position" required value={position} onChange={e => setPosition(e.target.value)} className="mt-2 h-11 w-full border bg-background px-3 text-sm"><option value="">Select a position</option>{positions.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div><div><label htmlFor="nominee-name" className="text-sm font-medium">Full name</label><Input id="nominee-name" required value={name} onChange={e => setName(e.target.value)} className="mt-2 h-11" /></div><div><label htmlFor="statement" className="text-sm font-medium">Statement</label><textarea id="statement" rows={5} value={statement} onChange={e => setStatement(e.target.value)} className="mt-2 w-full border bg-background p-3 text-sm" /></div><Button type="submit" disabled={pending || !position} className="h-11 w-full">{pending ? "Submitting…" : "Submit nomination"}</Button></form>}</main>;
}
